---
# tasks file for docker-ubuntu
- name: Install apt-transport-https, ca-certificates
  apt:
    name: "{{item}}"
    update_cache: yes
    install_recommends: no
  with_items:
  - apt-transport-https
  - ca-certificates
  become: "{{docker_nonroot}}"
- name: Add the new GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: "{{docker_nonroot}}"
- name: Template a sources.list
  template:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
  become: "{{docker_nonroot}}"
- name: Install the recommended package
  apt:
    name: linux-image-extra-{{ansible_kernel}}
    update_cache: yes
    install_recommends: no
  become: "{{docker_nonroot}}"
- name: Install docker-engine
  apt:
    name: docker-engine
    update_cache: yes
    install_recommends: no
  become: "{{docker_nonroot}}"
- name: Add the ubuntu user to the docker group
  user:
    name: "{{item}}"
    groups: docker
    append: yes
  become: "{{docker_nonroot}}"
  with_items: "{{docker_users}}"
