# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  ["14.04", "16.04", "17.04"].each{|version|
    config.vm.define version do |app|
      app.vm.box = "bento/ubuntu-#{version}"
      app.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
      end 
      app.vm.provision "ansible" do |ansible|
        ansible.playbook = "./test.yml"
      end
    end 
  }
end
